### ISSUE TITLE
模型在预测的时候是根据什么来判断的？

### ISSUE THREAD

**Issue by Yegiri** [AtmaHou/FewShotTagging#11]
请问这个模型在预测的时候是给出每个词属于每种标签的概率，然后选择概率最大的那个标签吗？
负例有没有考虑进去？

**Comment by AtmaHou** [comment]
Hi~
（1）序列标注问题 or slot tagging问题，是一个词级别的多分类问题（Multi-Classification Problem），不论是不是小样本问题，一般都是根据标签概率来选择标签的。
（2）序列标注一般不讨论负例的问题，我猜你想问的是“非槽位词”怎么处理，这些词会被归为一个统一的标签O，即others类别。预测时和有效标签一起算概率，然后预测。
