### ISSUE TITLE
使用的数据文件是现有的还是自己构造的呢？有相应的格式说明或者构造方法介绍？

### ISSUE THREAD

**Issue by readyFly** [AtmaHou/FewShotTagging#13]
如题

**Comment by AtmaHou** [comment]
hi，数据式我们自己构造的：
（1）数据集可以在readme中找到下载链接，序号是交叉验证号
（2）构造的算法可以在论文中找到
（3）数据构造代码和数据格式可以在这里找到：https://github.com/AtmaHou/MetaDialog#few-shot-data-construction-tool
