### ISSUE TITLE
实验可以不生成word_piece_marks、tokenized_texts、word_piece_labels吗？

### ISSUE THREAD

**Issue by Yegiri** [AtmaHou/FewShotTagging#16]
除了将word_piece_data设置成False，还有什么需要调整吗？

**Comment by AtmaHou** [comment]
- 不生成就需要在preprocessing里手动生成，
- 下面这个新版本的代码和readlme里面的新版本数据就已经做了这个事情了
https://github.com/AtmaHou/MetaDialog

**Comment by Yegiri** [comment]
run_1_shot_slot_tagging.sh这个脚本实现的就是L-Tapnet+CDT方法吗？

**Comment by AtmaHou** [comment]
> run_1_shot_slot_tagging.sh这个脚本实现的就是L-Tapnet+CDT方法吗？

是的，注意下载新的数据
