### ISSUE TITLE
Can not run script

### ISSUE THREAD

**Issue by ruleGreen** [AtmaHou/FewShotTagging#2]
![image](https://user-images.githubusercontent.com/26263128/84340925-6ee2df80-abd4-11ea-9448-b4eb8ab49f55.png)

![image](https://user-images.githubusercontent.com/26263128/84340947-7efabf00-abd4-11ea-935a-40c89ee0e65f.png)
![image](https://user-images.githubusercontent.com/26263128/84340990-a05bab00-abd4-11ea-94f6-490a6ccac07f.png)

结果和package信息如图

**Comment by AtmaHou** [comment]
A solution from the private message:
√ pip install pytorch-nlp
× pip install torchnlp
