### ISSUE TITLE
细节疑问

### ISSUE THREAD

**Issue by Wangpeiyi9979** [AtmaHou/FewShotTagging#23]
想请问一下，你们所说的N-Way是在什么粒度下的N-Way：

是把比如【Weather】当成一类，还是分开，【Weather】变为【B-Weather】、【I-Weather】成为两个类别

**Comment by Wangpeiyi9979** [comment]
以及，比如一个query，他的golden标签为，O，O，O，B-Weather，I-Weather， I-Weather，O，O，O
最后评测的时候，是在entity level算F1还是就在tag level算F1呢？

**Comment by AtmaHou** [comment]
1. 模型中【B-Weather】、【I-Weather】看成两个类别了
2. 模型评价的时候，我们直接使用了 conlleval的官方脚本，是算的span level的，即整个entity全对才算对，不能多，不能少
