### ISSUE TITLE
How to inspect prediction results?

### ISSUE THREAD

**Issue by chijames** [AtmaHou/FewShotTagging#24]
Hi,

Thanks for releasing the code! May I know how to perform inference on the saved checkpoints? Basically, I want to take a look at the predicted BIO results of all the test sentences.

Thanks!

**Comment by laiyongkui1997** [comment]
You can perform following steps:
1. delete the `--do_train` parameter, remain the `--do_predict` parameter
2. add `--saved_mode_path ${the_model_path}` to tell program where the checkpoint is
3. change `--output_dir ${the_prediction_result_saved_path}` to avoid covering the origin files.
4. change the log filename to avoid covering the origin log file.

**Comment by AtmaHou** [comment]
> You can perform following steps:
> 
> 1. delete the `--do_train` parameter, remain the `--do_predict` parameter
> 2. add `--saved_mode_path ${the_model_path}` to tell program where the checkpoint is
> 3. change `--output_dir ${the_prediction_result_saved_path}` to avoid covering the origin files.
> 4. change the log filename to avoid covering the origin log file.

Thanks for the prompt answer!
