### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wjczf123** [AtmaHou/FewShotTagging#28]
Hi, yutai. 

Why the size of support set is bigger than the size of query set sometimes in your dataset?

**Comment by AtmaHou** [comment]
There is no relation between the size of support and query sets. 

For example, a support set may be constructed according to x-shot rules of the Mini-Including Algorithm, while query sets may be randomly sampled to a fixed size.

**Comment by wjczf123** [comment]
Sorry, I said it wrong. I want to say 'why the size of label space in support set is bigger than the size of label spance in query set sometimes in your dataset?' For example, the label space in support set is [playtolist, playmusic, getweather]. But the label space in query set is only [playmusic, getweather].

**Comment by AtmaHou** [comment]
> Sorry, I said it wrong. I want to say 'why the size of label space in support set is bigger than the size of label spance in query set sometimes in your dataset?' For example, the label space in support set is [playtolist, playmusic, getweather]. But the label space in query set is only [playmusic, getweather].

OK. This has a similar answer to the previous question. Like the test set of many datasets, the query set is usually randomly sampled, and there is no guarantee that all tags will appear in these cases. Such random distribution of queries may better match the real-application situations.

**Comment by wjczf123** [comment]
I'm not sure.
Do you mean that the support set always has N-way and the query set sometimes smaller than N (for example, N-1)？

**Comment by AtmaHou** [comment]
Yep, especially when the query set is relatively small and is randomly sampled. If this is important to your model at training time, then you can just sample some larger queries or write rules to constrain it. But it is better to use existing queries or randomly sampled queries when testing to avoid breaking the natural distribution of tags.

**Comment by wjczf123** [comment]
OK. Thanks for your help.
