### ISSUE TITLE
请问这个任务可以用多个GPU跑吗？可以的话要怎么设置？

### ISSUE THREAD

**Issue by Yegiri** [AtmaHou/FewShotTagging#5]
如题。

**Comment by AtmaHou** [comment]
用脚本的话gpu标号直接用逗号隔开就好了，代码本身是默认使用所有可见的gpu。

训练是没有什么问题的，但是测试时有的环境下，在load多gpu模型时可能会报问题，所以建议优先跑单gpu，可以把seed分散到多个gpu分别跑，效果等效~
