### ISSUE TITLE
关于交叉检验

### ISSUE THREAD

**Issue by BillKiller** [AtmaHou/FewShotTagging#9]
我查看了代码后没有发现代码处理交叉检验的部分，想问下怎么设置参数让模型进行交叉检验？

**Comment by AtmaHou** [comment]
(1) 让模型直接做交叉检验耦合度太高，不是好的设计。
所以我们是用脚本和数据进行交叉检验的。
(2) bash 脚本中cross_id就是控制交叉检验的参数，它对应数据文件的数字~~

**Comment by BillKiller** [comment]
那做交叉检验的脚本在项目中有吗？是不是直接运行脚本就能交叉检验？

**Comment by AtmaHou** [comment]
是的，直接运行就好~~ 它会自动遍历setting和seed出结果~~
